### ISSUE TITLE
"Add new" form scrolling bug on FF Android

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#185]
mentioned in https://github.com/mozilla/network-pulse/pull/165#issuecomment-240513792

> Might be a Firefox Android specific bug, but if I open, close, and then re-open the submission form, it becomes unscrollable. Couldn't reproduce it in Chrome for Android.

**Comment by xmatthewx** [comment]
I believe this is fixed. True @mmmavis ?

**Comment by mmmavis** [comment]
Nope this is not fixed. It's a very specific bug that only happens on Android FF. 
> Might be a Firefox Android specific bug, but if I open, close, and then re-open the submission form, it becomes unscrollable. Couldn't reproduce it in Chrome for Android.

I couldn't seem to find what's causing the problem.

Reopen this ticket.

**Comment by mmmavis** [comment]
I cleared the milestone (feel free to change it)

**Comment by mmmavis** [comment]
v1 bug. closing.
